# Setup
title:               Explainable AI
tagline:             'a living literature review'
description:         'Current research on explainability and interpretability of machine learning algorithms'
url:                 https://xai_research.github.io
baseurl:             ''

collections:
  publications:
    output: true
    permalink: /:collection/:path/

plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
    style: compressed
